# Introduction to NumPy

Geir Arne Hjelle, geirarne@gmail.com

<https://github.com/gahjelle/numpy-introduction>

## Agenda

- The NumPy array
- Generating random numbers with NumPy
- Vectorized operations
- Linear algebra
- Broadcasting

In [1]:
import numpy as np

## The NumPy Array

You can convert lists and other iterables to NumPy arrays with `np.array()`:

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

All elements in a NumPy array must have the same datatype. `np.array()` will cast to a common datatype if possible:

In [3]:
np.array([1, 2.3, 4])

array([1. , 2.3, 4. ])

In [4]:
np.array([1, "a", True, 3.14])

array(['1', 'a', 'True', '3.14'], dtype='<U32')

Typically, you'll work with arrays of integers or floats.

NumPy arrays can have several dimensions:

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

A one-dimensional array often represents a vector and a two-dimensional array typically represents a matrix:

In [7]:
x = np.array([-1, 0, 2], dtype="float64")
A = np.array([[1, 0, 1], [0, 1, -1], [-1, 1, 0]])

In [8]:
x.ndim

1

In [9]:
A.ndim

2

In [10]:
x.shape

(3,)

In [11]:
A.shape

(3, 3)

There are functions that can create special arrays (<https://numpy.org/doc/stable/user/basics.creation.html>):

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [15]:
np.linspace(1, 2, 11)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

You can **index** NumPy arrays similarly to Python lists:

In [18]:
A[2]

array([-1,  1,  0])

In [19]:
A[0, 1]

0

Note that you can index into all dimensions by separating the indices by commas. Slices can also be used:

In [20]:
A[1:]

array([[ 0,  1, -1],
       [-1,  1,  0]])

In [21]:
A[1:, :1]

array([[ 0],
       [-1]])

In [22]:
A[:, 2]

array([ 1, -1,  0])

In [23]:
A[:, 2:3]

array([[ 1],
       [-1],
       [ 0]])

You can create new dimensions by indexing with `np.newaxis` (or `None`):

In [24]:
x[:, np.newaxis]

array([[-1.],
       [ 0.],
       [ 2.]])

In [25]:
x[np.newaxis, :]

array([[-1.,  0.,  2.]])

You can change the shape of an array with `.reshape()`:

In [26]:
x.reshape((3, 1))

array([[-1.],
       [ 0.],
       [ 2.]])

In [27]:
A.reshape(9)

array([ 1,  0,  1,  0,  1, -1, -1,  1,  0])

In [28]:
A.reshape(-1)

array([ 1,  0,  1,  0,  1, -1, -1,  1,  0])

Note that `-1` is a placeholder that can be used in one dimension to represent the "necessary number of elements".

## Generating Random Numbers

NumPy has a powerful mechanism for generating random numbers (<https://numpy.org/doc/stable/reference/random/index.html> and <https://realpython.com/numpy-random-number-generator/>):

In [29]:
rng = np.random.default_rng(seed=0xba5e1)
rng

Generator(PCG64) at 0x7F4DA018B680

An instance of a (pseudo)-random number generator (PRNG) can generate random numbers from many different distributions:

In [30]:
rng.uniform(0, 10)

7.4733807849662774

In [31]:
rng.uniform(0, 10, size=(3, 3))

array([[1.93899485, 8.6597296 , 7.51987487],
       [3.92921776, 6.05336418, 8.00385771],
       [4.98190324, 6.75017374, 4.94000277]])

In [32]:
rng.normal()

-0.8411429888224159

In [33]:
rng.normal(size=10)

array([-1.72390385, -0.78197317, -1.01104645, -0.1744181 ,  0.59087105,
       -0.92860242,  0.6989071 , -1.68148475, -1.73323795, -1.35514273])

In [34]:
rng.normal(10, 5, size=(2, 4))

array([[ 0.38239346,  3.184656  ,  1.40496407, -1.52121546],
       [ 9.88329585, 12.74914441, 11.33437718,  3.71635748]])

## Vectorized Operations

One of NumPy's absolute superpowers is that it supports **vectorized operations**:

In [35]:
x = np.arange(5)
y = np.array([-1, 0, 1, 0, -1])
A = rng.poisson(5, size=(3, 3))
A

array([[3, 4, 3],
       [5, 6, 2],
       [4, 3, 2]])

Operations on NumPy arrays are typically performed elementwise:

In [36]:
x + y

array([-1,  1,  3,  3,  3])

In [37]:
x * y

array([ 0,  0,  2,  0, -4])

In [38]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [39]:
np.cos(y)

array([0.54030231, 1.        , 0.54030231, 1.        , 0.54030231])

In [40]:
1 / A

array([[0.33333333, 0.25      , 0.33333333],
       [0.2       , 0.16666667, 0.5       ],
       [0.25      , 0.33333333, 0.5       ]])

**Side-note:** Vectorized operations means that you usually **DON'T** need to run loops when working with NumPy. This is important, especially for performance:

In [41]:
numbers_list = list(range(1_000_000))
numbers_array = np.array(numbers_list)

In [42]:
%%timeit
[x**2 for x in numbers_list]

41.2 ms ± 741 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [43]:
%%timeit
numbers_array**2

634 µs ± 9.32 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


`%%timeit` is a special Jupyter/IPython command that allows you to do simple benchmarking of code cells.

Some operators work on the whole array:

In [44]:
x @ y

-2

The `@` operator performs dot-products on vectors. It'll do matrix multiplication if applied on a matrix:

In [45]:
z = np.array([1, 0, -1])
A

array([[3, 4, 3],
       [5, 6, 2],
       [4, 3, 2]])

In [46]:
A @ z

array([0, 3, 2])

In [47]:
z @ A

array([-1,  1,  1])

In [48]:
A @ A

array([[41, 45, 23],
       [53, 62, 31],
       [35, 40, 22]])

## Linear Algebra

NumPy is a great tool for doing linear algebra. There are several dedicated functions in the `np.linalg` module:

In [49]:
np.linalg.det(A)

-17.0

In [50]:
np.linalg.norm(A)

11.313708498984761

In [51]:
np.linalg.inv(A)

array([[-0.35294118, -0.05882353,  0.58823529],
       [ 0.11764706,  0.35294118, -0.52941176],
       [ 0.52941176, -0.41176471,  0.11764706]])

In [52]:
np.linalg.inv(A) @ A

array([[ 1.00000000e+00,  5.55111512e-16,  2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  8.32667268e-17,  1.00000000e+00]])

In [68]:
A.T

array([[2, 3, 5],
       [7, 4, 8],
       [7, 2, 6]])

In practice, you more often work with non-square matrices. The **pseudoinverse** is useful in these cases:

In [53]:
A = np.array([[1, 2], [3, 0], [0, 2]])
b = np.array([30, 15, 20])

This represents the matrix and vector

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 0 \\ 0 & 2 \end{bmatrix}, \
b = \begin{pmatrix} 30 \\ 15 \\ 20 \end{pmatrix}
$$

Consider the equation $Ax = b$ which can be expressed as the following:

$$
\begin{align}
u + 2 v &= 30 \\
3u &= 15 \\
2v &= 20
\end{align}
$$

Note that $x = (5, 10)$ or $u = 5$, $v = 10$ would be the solution to the system represented by the last two rows of $A$ and $b$. This is not consistent with the first row, so there is no exact solution to the equation $Ax = b$.

In [54]:
np.linalg.pinv(A)

array([[ 0.05263158,  0.31578947, -0.05263158],
       [ 0.23684211, -0.07894737,  0.26315789]])

In [55]:
np.linalg.pinv(A) @ b

array([ 5.26315789, 11.18421053])

In [56]:
np.linalg.lstsq(A, b, rcond=None)

(array([ 5.26315789, 11.18421053]),
 array([11.84210526]),
 2,
 array([3.35202446, 2.60075605]))

See <RP> for more information.

## Broadcasting

Broadcasting is a cousin of vectorization and makes many operations in NumPy extra powerful.

In short, in many cases, NumPy can adapt the shape of an array to make it consistent with another.

In [57]:
A = rng.poisson(5, size=(3, 3))
x = np.arange(2, 7, 2)
A, x

(array([[2, 7, 7],
        [3, 4, 2],
        [5, 8, 6]]),
 array([2, 4, 6]))

In [58]:
A + A

array([[ 4, 14, 14],
       [ 6,  8,  4],
       [10, 16, 12]])

In [59]:
A + x

array([[ 4, 11, 13],
       [ 5,  8,  8],
       [ 7, 12, 12]])

Even though `x` is one-dimensional, it's broadcast into two dimensions. The first element of `x` is added to every element in the first column of `A`. The second element of `x` is added to every element in the second column of `A` and so on.

A common usecase for broadcasting is for applying operations with scalars:

In [60]:
3 * A

array([[ 6, 21, 21],
       [ 9, 12,  6],
       [15, 24, 18]])

In [61]:
x - 2

array([0, 2, 4])

In [62]:
A * x - 10 / x

array([[-1.        , 25.5       , 40.33333333],
       [ 1.        , 13.5       , 10.33333333],
       [ 5.        , 29.5       , 34.33333333]])

In operations that require "compatible" arrays, broadcasting works by comparing shapes starting at the "last" dimension. If one array has **one** element in that dimension, it will be broadcast to match the other array.

In [63]:
B = np.ones((4, 3, 2), dtype="int8")

In [64]:
B + np.arange(4).reshape(4, 1, 1)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3],
        [3, 3]],

       [[4, 4],
        [4, 4],
        [4, 4]]])

In [65]:
B + np.arange(8).reshape(4, 1, 2)

array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[3, 4],
        [3, 4],
        [3, 4]],

       [[5, 6],
        [5, 6],
        [5, 6]],

       [[7, 8],
        [7, 8],
        [7, 8]]])

You can use `np.newaxis` to control the broadcasting:

In [66]:
A + x[:, np.newaxis]

array([[ 4,  9,  9],
       [ 7,  8,  6],
       [11, 14, 12]])

In [67]:
A + x[np.newaxis, :]

array([[ 4, 11, 13],
       [ 5,  8,  8],
       [ 7, 12, 12]])