# Exercises: NumPy Arrays

In [1]:
import numpy as np

## 1. Create a specific array

Create an array representing the following matrix with NumPy:

$$
\begin{bmatrix}
  1 &  4 & -2 &  1 \\
  2 & -1 &  0 &  3 \\
  0 &  0 &  1 &  9
\end{bmatrix}
$$

In [2]:
np.array([[1, 4, -2, 1], [2, -1, 0, 3], [0, 0, 1, 9]])

array([[ 1,  4, -2,  1],
       [ 2, -1,  0,  3],
       [ 0,  0,  1,  9]])

## 2. Play with data types

Create the same array as above, but make sure each element is a floating point number.

In [3]:
np.array([[1, 4, -2, 1], [2, -1, 0, 3], [0, 0, 1, 9]], dtype="float64")

array([[ 1.,  4., -2.,  1.],
       [ 2., -1.,  0.,  3.],
       [ 0.,  0.,  1.,  9.]])

In [4]:
np.array([[1.0, 4, -2, 1], [2, -1, 0, 3], [0, 0, 1, 9]])

array([[ 1.,  4., -2.,  1.],
       [ 2., -1.,  0.,  3.],
       [ 0.,  0.,  1.,  9.]])

## 3. Prepare an array of a specific shape

Create an array with all elements being `0` with the same shape as the array in exercise 1.

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
A = np.array([[1, 4, -2, 1], [2, -1, 0, 3], [0, 0, 1, 9]])
np.zeros_like(A)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 4. Create a constant array

Create an array with 5 rows and 2 columns where all elements have the value `3.14`.

In [7]:
np.ones((5, 2)) * 3.14

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [8]:
np.full((5, 2), 3.14)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])