# Exercises: Random Numbers

In [1]:
import numpy as np

## 1. Create a Pseudo-Random Number Generator (PRNG) instance

Create a PRNG and name it `rng`. Don't use a seed. Create several random numbers with `rng.random()`.
Then, create a new, seedless `rng` and create several new random numbers. Note that these are different from before.

In [2]:
rng = np.random.default_rng()

In [3]:
rng.random()

0.2736845674068784

In [4]:
rng.random()

0.5498593418825777

In [5]:
rng.random()

0.7712279195932138

In [6]:
rng = np.random.default_rng()

In [7]:
rng.random()

0.595765222962484

In [8]:
rng.random()

0.7433689112551417

In [9]:
rng.random()

0.3441534534725339

## 2. Work with seeds

Create a PRNG and seed it with a fixed number. Create a vector of 5 random normal-distributed numbers.
Then, create a new PRNG with the same seed, and create a new vector of 5 random normal-distributed numbers. Observe that the numbers are identical to before.

Finally, create a PRNG with a different seed and use it to create a new vector of 5 random normal-distributed numbers.

In [10]:
rng = np.random.default_rng(seed=2023)

In [11]:
rng.normal(size=5)

array([ 0.60172129,  1.15161897, -1.35946236,  0.22205533, -0.77586755])

In [12]:
rng = np.random.default_rng(seed=2023)

In [13]:
rng.normal(size=5)

array([ 0.60172129,  1.15161897, -1.35946236,  0.22205533, -0.77586755])

In [14]:
rng = np.random.default_rng(seed=2024)

In [15]:
rng.normal(size=5)

array([ 1.02885687,  1.64192004,  1.14671953, -0.97317952, -1.3928001 ])

## 3. Sample from a list of numbers

Create an array named `squares` that contains the square numbers _0², 1², 2², ..., 9²_.
Use a PRNG (`rng.choice()`) to sample 20 numbers from `squares`.

In [16]:
squares = np.arange(10)**2

In [17]:
rng = np.random.default_rng(seed=2023)

In [18]:
rng.choice(squares, size=20, replace=True)

array([16,  0,  1,  4,  4,  1, 25, 16,  4, 36,  0, 25,  4, 49,  4, 25, 16,
       64,  1,  1])