# Exercises: Vectorized Operations

In [1]:
import numpy as np

## 1. Find values of a function

Create an array `x` of length 201 with values from `-10` to `10`. Compute the following functions:

- $f(x) = x^2$
- $f(x) = \log x$ (What happens for invalid values of $x$?)
- $f(x) = 1 + 2 \sin x$ 

In [2]:
x = np.linspace(-10, 10, 201)

In [3]:
x**2

array([1.000e+02, 9.801e+01, 9.604e+01, 9.409e+01, 9.216e+01, 9.025e+01,
       8.836e+01, 8.649e+01, 8.464e+01, 8.281e+01, 8.100e+01, 7.921e+01,
       7.744e+01, 7.569e+01, 7.396e+01, 7.225e+01, 7.056e+01, 6.889e+01,
       6.724e+01, 6.561e+01, 6.400e+01, 6.241e+01, 6.084e+01, 5.929e+01,
       5.776e+01, 5.625e+01, 5.476e+01, 5.329e+01, 5.184e+01, 5.041e+01,
       4.900e+01, 4.761e+01, 4.624e+01, 4.489e+01, 4.356e+01, 4.225e+01,
       4.096e+01, 3.969e+01, 3.844e+01, 3.721e+01, 3.600e+01, 3.481e+01,
       3.364e+01, 3.249e+01, 3.136e+01, 3.025e+01, 2.916e+01, 2.809e+01,
       2.704e+01, 2.601e+01, 2.500e+01, 2.401e+01, 2.304e+01, 2.209e+01,
       2.116e+01, 2.025e+01, 1.936e+01, 1.849e+01, 1.764e+01, 1.681e+01,
       1.600e+01, 1.521e+01, 1.444e+01, 1.369e+01, 1.296e+01, 1.225e+01,
       1.156e+01, 1.089e+01, 1.024e+01, 9.610e+00, 9.000e+00, 8.410e+00,
       7.840e+00, 7.290e+00, 6.760e+00, 6.250e+00, 5.760e+00, 5.290e+00,
       4.840e+00, 4.410e+00, 4.000e+00, 3.610e+00, 

In [4]:
np.log(x)

/tmp/ipykernel_1290119/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)
/tmp/ipykernel_1290119/1277889159.py:1: RuntimeWarning: invalid value encountered in log
  np.log(x)


array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,      

In [5]:
1 + 2 * np.sin(x)

array([ 2.08804222e+00,  1.91507179e+00,  1.73295826e+00,  1.54352125e+00,
        1.34865356e+00,  1.15030224e+00,  9.50449149e-01,  7.51091153e-01,
        5.54220172e-01,  3.61803275e-01,  1.75763030e-01, -2.04171292e-03,
       -1.69834386e-01, -3.25938460e-01, -4.68794196e-01, -5.96974225e-01,
       -7.09197816e-01, -8.04343668e-01, -8.81461113e-01, -9.39779622e-01,
       -9.78716493e-01, -9.97882684e-01, -9.97086691e-01, -9.76336468e-01,
       -9.35839344e-01, -8.75999954e-01, -7.97416192e-01, -7.00873241e-01,
       -5.87335728e-01, -4.57938080e-01, -3.13973197e-01, -1.56879529e-01,
        1.17732977e-02,  1.90300159e-01,  3.76917273e-01,  5.69760024e-01,
        7.66901590e-01,  9.66372199e-01,  1.16617881e+00,  1.36432501e+00,
        1.55883100e+00,  1.74775333e+00,  1.92920436e+00,  2.10137109e+00,
        2.26253328e+00,  2.41108065e+00,  2.54552898e+00,  2.66453488e+00,
        2.76690931e+00,  2.85162936e+00,  2.91784855e+00,  2.96490523e+00,
        2.99232922e+00,  

## 2. Compare vectorized and non-vectorized code

Redo the previous exercise for one of the functions, but this time solve it using an explicit loop instead of vectorization.

How do the two solutions compare in terms of **readability** and **performance**?

In [6]:
np.array([1 + 2 * np.sin(n) for n in x])

array([ 2.08804222e+00,  1.91507179e+00,  1.73295826e+00,  1.54352125e+00,
        1.34865356e+00,  1.15030224e+00,  9.50449149e-01,  7.51091153e-01,
        5.54220172e-01,  3.61803275e-01,  1.75763030e-01, -2.04171292e-03,
       -1.69834386e-01, -3.25938460e-01, -4.68794196e-01, -5.96974225e-01,
       -7.09197816e-01, -8.04343668e-01, -8.81461113e-01, -9.39779622e-01,
       -9.78716493e-01, -9.97882684e-01, -9.97086691e-01, -9.76336468e-01,
       -9.35839344e-01, -8.75999954e-01, -7.97416192e-01, -7.00873241e-01,
       -5.87335728e-01, -4.57938080e-01, -3.13973197e-01, -1.56879529e-01,
        1.17732977e-02,  1.90300159e-01,  3.76917273e-01,  5.69760024e-01,
        7.66901590e-01,  9.66372199e-01,  1.16617881e+00,  1.36432501e+00,
        1.55883100e+00,  1.74775333e+00,  1.92920436e+00,  2.10137109e+00,
        2.26253328e+00,  2.41108065e+00,  2.54552898e+00,  2.66453488e+00,
        2.76690931e+00,  2.85162936e+00,  2.91784855e+00,  2.96490523e+00,
        2.99232922e+00,  

In [7]:
%%timeit
1 + 2 * np.sin(x)

4.09 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%%timeit
np.array([1 + 2 * np.sin(n) for n in x])

148 µs ± 497 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
