# Exercises: Linear Algebra

In [1]:
import numpy as np

## 1. Linear algebra operations

Create the following matrix:

$$
A = \begin{bmatrix}
   1 &  2 & -1 \\
  -1 & -1 &  2 \\
   3 &  0 & -1
\end{bmatrix}
$$

Calculate the following:

- The transpose of $A$
- The determinant of $A$
- The inverse of $A$
- The square of $A$, i.e. $A$ multiplied by itself

In [2]:
A = np.array([[1, 2, -1], [-1, -1, 2], [3, 0, -1]])

In [3]:
A.T

array([[ 1, -1,  3],
       [ 2, -1,  0],
       [-1,  2, -1]])

In [4]:
np.linalg.det(A)

7.999999999999998

In [5]:
np.linalg.inv(A)

array([[ 0.125,  0.25 ,  0.375],
       [ 0.625,  0.25 , -0.125],
       [ 0.375,  0.75 ,  0.125]])

In [6]:
A @ A

array([[-4,  0,  4],
       [ 6, -1, -3],
       [ 0,  6, -2]])

## 2. Least-square equations

Find the least-square solution to the following system:

$$
\begin{bmatrix}
   1 &  2 & -1 \\
  -1 & -1 &  2 \\
   3 &  0 & -1 \\
   2 & -1 &  0 \\
   0 &  1 & -2
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}
= \begin{bmatrix} 10 \\ 15 \\ 20 \\ 25 \\ 30 \end{bmatrix}
$$

In [7]:
A = np.array([[1, 2, -1], [-1, -1, 2], [3, 0, -1], [2, -1, 0], [0, 1, -2]])
b = np.array([10, 15, 20, 25, 30])

In [8]:
np.linalg.pinv(A) @ b

array([ 5.21875, -3.65625, -5.0625 ])

In [9]:
np.linalg.lstsq(A, b, rcond=None)

(array([ 5.21875, -3.65625, -5.0625 ]),
 array([1434.84375]),
 3,
 array([4.52039613, 3.16227766, 1.25140676]))