# Exercises: Broadcasting

In [1]:
import numpy as np

## 1. Combine arrays and scalars

Create a random $4 \times 2$ array named $A$. Calculate the following expressions:

- $A + 1$
- $3A$
- $2A - 3$

Make sure you understand the results.

In [2]:
rng = np.random.default_rng(seed=2023)
A = rng.poisson(3, size=(4, 2))
A

array([[1, 2],
       [4, 3],
       [4, 5],
       [7, 5]])

In [3]:
A + 1

array([[2, 3],
       [5, 4],
       [5, 6],
       [8, 6]])

In [4]:
3 * A

array([[ 3,  6],
       [12,  9],
       [12, 15],
       [21, 15]])

In [5]:
2 * A - 3

array([[-1,  1],
       [ 5,  3],
       [ 5,  7],
       [11,  7]])

## 2. Combine 2-D and 1-D arrays

Create a random $3 \times 4$ array $A$, a random $3$ array $x$, and a random $4$ array $y$.

Which of the following expressions are allowed? Why?

- `A + x`
- `A * y` (elementwise multiplication)
- `A * x[:, np.newaxis]`
- `A - y[:, np.newaxis]`

In [6]:
A = rng.poisson(3, size=(3, 4))
x = rng.poisson(3, size=3)
y = rng.poisson(3, size=4)

In [7]:
# A + x  # Not allowed because the last dimensions are not compatible (A: 4, x: 3)

In [8]:
A * y

array([[12,  2,  3,  3],
       [ 9,  8,  3,  9],
       [ 6,  8,  2, 18]])

In [9]:
A * x[:, np.newaxis]

array([[16,  4, 12,  4],
       [ 9, 12,  9,  9],
       [ 8, 16,  8, 24]])

In [10]:
# A - y[:, np.newaxis]  # Not allowed because second-to-last dimensions are not compatible - but y[np.newaxis, :] would be allowed

## 3. Higher dimensions

Create a random $5 \times 3 \times 3$ array. You can think of this as a vector of five $3 \times 3$ matrices.

Calculate the dot product of each of these five matrices with the vector $[1 \, 2 \, 3]$.

In [11]:
A = rng.poisson(3, size=(5, 3, 3))
A

array([[[4, 1, 2],
        [4, 2, 1],
        [6, 0, 3]],

       [[1, 5, 1],
        [5, 3, 4],
        [2, 6, 3]],

       [[5, 4, 2],
        [4, 1, 2],
        [2, 2, 4]],

       [[1, 4, 3],
        [3, 2, 4],
        [1, 5, 3]],

       [[4, 1, 4],
        [2, 2, 3],
        [2, 2, 3]]])

In [12]:
A @ np.array([1, 2, 3])

array([[12, 11, 15],
       [14, 23, 23],
       [19, 12, 18],
       [18, 19, 20],
       [18, 15, 15]])

In [13]:
A[0] @ np.array([1, 2, 3])

array([12, 11, 15])